sudo: false
language: python
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- 'pypy'

install:
- pip install tox
- TOX_ENV=${TRAVIS_PYTHON_VERSION/[0-9].[0-9]/py${TRAVIS_PYTHON_VERSION/.}}
script: tox -e $TOX_ENV
before_cache:
- rm -rf $HOME/.cache/pip/log
cache:
  directories:
  - $HOME/.cache/pip
deploy:
  provider: pypi
  user: mattcl
  password:
    secure: "Ih1/tmpnpbUxXRRhc9+BdPvnBrGbJh/M8wGZansdC53s/H7j1DPOeJQfgAfpLhYW2FyxblDKbTuDyrnm6hvgp/xIQfrDk7L2yEbJQa9641ox5gJLG8po65DnGD4ydKWqOWvRJNIX7U83b9osblV4ZTcwqA3Sn/DIXutnbmeBmNuVgissYgjeysYvcyMHOuPe5sdg48gLbYYSOMhEZJ25YdJy7W6+bzbF41RP4UnffndcmUl10DuEch3ROW4KHLWypwkDA0KBvbOtyn7Xc7SqBiTrJ3WukxJEHbwPrZQn1MNcLd6qgonB0nyydi/NTk6AVkkv4CHvx9zOOAbLucPgjlYF5keGiGqKDJ/Kpz9+LIqvLD9JLR9AypqBL7zK0mCLSfA8hI6N+RPDVeyoNrfIkCCn0K+6eU8TGhAZ6W/IbsWC0i5r98ec/Iddv0YKlNqOvZEu1TooKoGuvW0kHgAVT/Aw/en9159gK4yhkNQOL9LQ2XijqXshcXZYPJa8ydvLKz9KrsnmqF9E4sZtt3qlMFc4QQntgPb4xwqKDDEKn4s8frR2fvv24oWCEXJInKOrUEuGlXNB7lz2IDNia9Qslq3zznAnZZEuxqpiFEgHLaRHzOeh5nFYl9EGAI6eRR/alf03KqPOt+g2oNSzkfE9AC9Y7lOMoKMyIlSnWQ25m4g="
  on:
    tags: true
    branch: master
